trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PRISMA_API_URL: https://api4.prismacloud.io

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: Install Checkov
  - script: checkov -d . --use-enforcement-rules --bc-api-key 9af59893-a10a-44fc-96d0-fb95e7ac0728::+1zco0yDoQo7J3LEHAQrp5prGyo= --repo-id hacksawduggan/PaloAltoADO --branch main -o cli -o junitxml --output-file-path console,CheckovReport.xml
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Run Checkov
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/CheckovReport.xml'
      testRunTitle: PrismaCloudTests
    displayName: Publish Test Results
    condition: always()
